### ISSUE TITLE
Hindcast vs. Archive conflation, clarification

### ISSUE THREAD

**Issue by adamkemberling** [BigelowLab/fvcom#8]
In this section during the README:

There are a number of models with a Gulf of Maine bend including [forecasts](http://www.smast.umassd.edu:8080/thredds/forecasts.html) and [archives](http://www.smast.umassd.edu:8080/thredds/catalog/models/fvcom/NECOFS/Archive/NECOFS_GOM/catalog.html)

The above link to "archives" are actually of forecast* archives. These are different from "hindcasts" which assimilate additional information after the fact and are better proxies of unobserved environmental states. 

Hindcast data isn't available past 2018 at the time of this issue: http://www.smast.umassd.edu:8080/thredds/catalog/models/fvcom/NECOFS/Archive/Seaplan_33_Hindcast_v1/catalog.html.

I only know this because I made the mistake of thinking I could combine hindcasts from 1978-2016 with the NECOFS forecast archive you linked to...

**Comment by btupper** [comment]
Oh, I see.  I have added you to the repos.  You ok to update the docs?

**Comment by jebyrnes** [comment]
Wait, I'm unclear - the link above for actual hundcasts has files that look like they go into the 1970s..... are these not hindcasts?

BTW - I haven't dug in hard yet, but I really want to use this package to start digging into wave data, and I'm so thankful for what y'all are doing here.

**Comment by adamkemberling** [comment]
[Hindcasts](http://www.smast.umassd.edu:8080/thredds/catalog/models/fvcom/NECOFS/Archive/Seaplan_33_Hindcast_v1/catalog.html) are available from 1978 through the end of :
2018 (hourly timestep)
2016 (daily timestep)
2017 (monthly timestep)

And depending on which timestep, the FVCOM mesh after 2016 will vary between some combination of GOM4 and GOM5 mesh versions.

[NECOFS forecast archives](http://www.smast.umassd.edu:8080/thredds/catalog/models/fvcom/NECOFS/Archive/NECOFS_GOM/catalog.html) are available for 2016 -  February of 2023 and all use the GOM4 mesh.

**Comment by adamkemberling** [comment]
I am inclined to close this for now, knowing that it still probably is imperfect.

**Comment by btupper** [comment]
That’s sort of the status of the whole thing… in progress!
